--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
____exports.PlaydateColor = PlaydateColor or ({})
____exports.PlaydateColor.Black = 0
____exports.PlaydateColor[____exports.PlaydateColor.Black] = "Black"
____exports.PlaydateColor.White = 1
____exports.PlaydateColor[____exports.PlaydateColor.White] = "White"
____exports.PlaydateColor.Clear = 2
____exports.PlaydateColor[____exports.PlaydateColor.Clear] = "Clear"
____exports.PlaydateColor.XOR = 3
____exports.PlaydateColor[____exports.PlaydateColor.XOR] = "XOR"
____exports.PlaydateFlip = PlaydateFlip or ({})
____exports.PlaydateFlip.Unflipped = 0
____exports.PlaydateFlip[____exports.PlaydateFlip.Unflipped] = "Unflipped"
____exports.PlaydateFlip.FlippedX = 1
____exports.PlaydateFlip[____exports.PlaydateFlip.FlippedX] = "FlippedX"
____exports.PlaydateFlip.FlippedY = 2
____exports.PlaydateFlip[____exports.PlaydateFlip.FlippedY] = "FlippedY"
____exports.PlaydateFlip.FlippedXY = 3
____exports.PlaydateFlip[____exports.PlaydateFlip.FlippedXY] = "FlippedXY"
____exports.PlaydatePolygonFill = PlaydatePolygonFill or ({})
____exports.PlaydatePolygonFill.NonZero = 0
____exports.PlaydatePolygonFill[____exports.PlaydatePolygonFill.NonZero] = "NonZero"
____exports.PlaydatePolygonFill.EvenOdd = 1
____exports.PlaydatePolygonFill[____exports.PlaydatePolygonFill.EvenOdd] = "EvenOdd"
____exports.PlaydateButton = PlaydateButton or ({})
____exports.PlaydateButton.Left = 1
____exports.PlaydateButton[____exports.PlaydateButton.Left] = "Left"
____exports.PlaydateButton.Right = 2
____exports.PlaydateButton[____exports.PlaydateButton.Right] = "Right"
____exports.PlaydateButton.Up = 4
____exports.PlaydateButton[____exports.PlaydateButton.Up] = "Up"
____exports.PlaydateButton.Down = 8
____exports.PlaydateButton[____exports.PlaydateButton.Down] = "Down"
____exports.PlaydateButton.B = 16
____exports.PlaydateButton[____exports.PlaydateButton.B] = "B"
____exports.PlaydateButton.A = 32
____exports.PlaydateButton[____exports.PlaydateButton.A] = "A"
____exports.PlaydateLanguage = PlaydateLanguage or ({})
____exports.PlaydateLanguage.English = 0
____exports.PlaydateLanguage[____exports.PlaydateLanguage.English] = "English"
____exports.PlaydateLanguage.Japanese = 1
____exports.PlaydateLanguage[____exports.PlaydateLanguage.Japanese] = "Japanese"
____exports.PlaydateFileOpenMode = PlaydateFileOpenMode or ({})
____exports.PlaydateFileOpenMode.Read = 3
____exports.PlaydateFileOpenMode[____exports.PlaydateFileOpenMode.Read] = "Read"
____exports.PlaydateFileOpenMode.Write = 4
____exports.PlaydateFileOpenMode[____exports.PlaydateFileOpenMode.Write] = "Write"
____exports.PlaydateFileOpenMode.Append = 8
____exports.PlaydateFileOpenMode[____exports.PlaydateFileOpenMode.Append] = "Append"
____exports.PlaydateDitherType = PlaydateDitherType or ({})
____exports.PlaydateDitherType.None = 0
____exports.PlaydateDitherType[____exports.PlaydateDitherType.None] = "None"
____exports.PlaydateDitherType.DiagonalLine = 1
____exports.PlaydateDitherType[____exports.PlaydateDitherType.DiagonalLine] = "DiagonalLine"
____exports.PlaydateDitherType.VerticalLine = 2
____exports.PlaydateDitherType[____exports.PlaydateDitherType.VerticalLine] = "VerticalLine"
____exports.PlaydateDitherType.HorizontalLine = 3
____exports.PlaydateDitherType[____exports.PlaydateDitherType.HorizontalLine] = "HorizontalLine"
____exports.PlaydateDitherType.Screen = 4
____exports.PlaydateDitherType[____exports.PlaydateDitherType.Screen] = "Screen"
____exports.PlaydateDitherType.Bayer2x2 = 5
____exports.PlaydateDitherType[____exports.PlaydateDitherType.Bayer2x2] = "Bayer2x2"
____exports.PlaydateDitherType.Bayer4x4 = 6
____exports.PlaydateDitherType[____exports.PlaydateDitherType.Bayer4x4] = "Bayer4x4"
____exports.PlaydateDitherType.Bayer8x8 = 7
____exports.PlaydateDitherType[____exports.PlaydateDitherType.Bayer8x8] = "Bayer8x8"
____exports.PlaydateDitherType.FloydSteinberg = 8
____exports.PlaydateDitherType[____exports.PlaydateDitherType.FloydSteinberg] = "FloydSteinberg"
____exports.PlaydateDitherType.Burkes = 9
____exports.PlaydateDitherType[____exports.PlaydateDitherType.Burkes] = "Burkes"
____exports.PlaydateDitherType.Atkinson = 10
____exports.PlaydateDitherType[____exports.PlaydateDitherType.Atkinson] = "Atkinson"
____exports.PlaydateLineCapStyle = PlaydateLineCapStyle or ({})
____exports.PlaydateLineCapStyle.Butt = 0
____exports.PlaydateLineCapStyle[____exports.PlaydateLineCapStyle.Butt] = "Butt"
____exports.PlaydateLineCapStyle.Square = 1
____exports.PlaydateLineCapStyle[____exports.PlaydateLineCapStyle.Square] = "Square"
____exports.PlaydateLineCapStyle.Round = 2
____exports.PlaydateLineCapStyle[____exports.PlaydateLineCapStyle.Round] = "Round"
____exports.PlaydateDrawMode = PlaydateDrawMode or ({})
____exports.PlaydateDrawMode.Copy = 0
____exports.PlaydateDrawMode[____exports.PlaydateDrawMode.Copy] = "Copy"
____exports.PlaydateDrawMode.WhiteTransparent = 1
____exports.PlaydateDrawMode[____exports.PlaydateDrawMode.WhiteTransparent] = "WhiteTransparent"
____exports.PlaydateDrawMode.BlackTransparent = 2
____exports.PlaydateDrawMode[____exports.PlaydateDrawMode.BlackTransparent] = "BlackTransparent"
____exports.PlaydateDrawMode.FillWhite = 3
____exports.PlaydateDrawMode[____exports.PlaydateDrawMode.FillWhite] = "FillWhite"
____exports.PlaydateDrawMode.FillBlack = 4
____exports.PlaydateDrawMode[____exports.PlaydateDrawMode.FillBlack] = "FillBlack"
____exports.PlaydateDrawMode.XOR = 5
____exports.PlaydateDrawMode[____exports.PlaydateDrawMode.XOR] = "XOR"
____exports.PlaydateDrawMode.NXOR = 6
____exports.PlaydateDrawMode[____exports.PlaydateDrawMode.NXOR] = "NXOR"
____exports.PlaydateDrawMode.Inverted = 7
____exports.PlaydateDrawMode[____exports.PlaydateDrawMode.Inverted] = "Inverted"
____exports.PlaydateStrokeLocation = PlaydateStrokeLocation or ({})
____exports.PlaydateStrokeLocation.Centered = 0
____exports.PlaydateStrokeLocation[____exports.PlaydateStrokeLocation.Centered] = "Centered"
____exports.PlaydateStrokeLocation.Inside = 1
____exports.PlaydateStrokeLocation[____exports.PlaydateStrokeLocation.Inside] = "Inside"
____exports.PlaydateStrokeLocation.Outside = 2
____exports.PlaydateStrokeLocation[____exports.PlaydateStrokeLocation.Outside] = "Outside"
____exports.PlaydateFontVariant = PlaydateFontVariant or ({})
____exports.PlaydateFontVariant.Normal = 0
____exports.PlaydateFontVariant[____exports.PlaydateFontVariant.Normal] = "Normal"
____exports.PlaydateFontVariant.Bold = 1
____exports.PlaydateFontVariant[____exports.PlaydateFontVariant.Bold] = "Bold"
____exports.PlaydateFontVariant.Italic = 2
____exports.PlaydateFontVariant[____exports.PlaydateFontVariant.Italic] = "Italic"
____exports.PlaydateTextAlignment = PlaydateTextAlignment or ({})
____exports.PlaydateTextAlignment.Left = 0
____exports.PlaydateTextAlignment[____exports.PlaydateTextAlignment.Left] = "Left"
____exports.PlaydateTextAlignment.Right = 1
____exports.PlaydateTextAlignment[____exports.PlaydateTextAlignment.Right] = "Right"
____exports.PlaydateTextAlignment.Center = 2
____exports.PlaydateTextAlignment[____exports.PlaydateTextAlignment.Center] = "Center"
____exports.PlaydateCollisionResponse = PlaydateCollisionResponse or ({})
____exports.PlaydateCollisionResponse.Slide = 0
____exports.PlaydateCollisionResponse[____exports.PlaydateCollisionResponse.Slide] = "Slide"
____exports.PlaydateCollisionResponse.Freeze = 1
____exports.PlaydateCollisionResponse[____exports.PlaydateCollisionResponse.Freeze] = "Freeze"
____exports.PlaydateCollisionResponse.Overlap = 2
____exports.PlaydateCollisionResponse[____exports.PlaydateCollisionResponse.Overlap] = "Overlap"
____exports.PlaydateCollisionResponse.Bounce = 3
____exports.PlaydateCollisionResponse[____exports.PlaydateCollisionResponse.Bounce] = "Bounce"
____exports.PlaydateCapitalizationBehavior = PlaydateCapitalizationBehavior or ({})
____exports.PlaydateCapitalizationBehavior.Normal = 1
____exports.PlaydateCapitalizationBehavior[____exports.PlaydateCapitalizationBehavior.Normal] = "Normal"
____exports.PlaydateCapitalizationBehavior.Words = 2
____exports.PlaydateCapitalizationBehavior[____exports.PlaydateCapitalizationBehavior.Words] = "Words"
____exports.PlaydateCapitalizationBehavior.Sentences = 3
____exports.PlaydateCapitalizationBehavior[____exports.PlaydateCapitalizationBehavior.Sentences] = "Sentences"
____exports.PlaydateSoundFormat = PlaydateSoundFormat or ({})
____exports.PlaydateSoundFormat["8bitMono"] = 0
____exports.PlaydateSoundFormat[____exports.PlaydateSoundFormat["8bitMono"]] = "8bitMono"
____exports.PlaydateSoundFormat["8bitStereo"] = 1
____exports.PlaydateSoundFormat[____exports.PlaydateSoundFormat["8bitStereo"]] = "8bitStereo"
____exports.PlaydateSoundFormat["16bitMono"] = 2
____exports.PlaydateSoundFormat[____exports.PlaydateSoundFormat["16bitMono"]] = "16bitMono"
____exports.PlaydateSoundFormat["16bitStereo"] = 3
____exports.PlaydateSoundFormat[____exports.PlaydateSoundFormat["16bitStereo"]] = "16bitStereo"
____exports.PlaydateSoundWave = PlaydateSoundWave or ({})
____exports.PlaydateSoundWave.Square = 0
____exports.PlaydateSoundWave[____exports.PlaydateSoundWave.Square] = "Square"
____exports.PlaydateSoundWave.Triangle = 1
____exports.PlaydateSoundWave[____exports.PlaydateSoundWave.Triangle] = "Triangle"
____exports.PlaydateSoundWave.Sine = 2
____exports.PlaydateSoundWave[____exports.PlaydateSoundWave.Sine] = "Sine"
____exports.PlaydateSoundWave.Noise = 3
____exports.PlaydateSoundWave[____exports.PlaydateSoundWave.Noise] = "Noise"
____exports.PlaydateSoundWave.Sawtooth = 4
____exports.PlaydateSoundWave[____exports.PlaydateSoundWave.Sawtooth] = "Sawtooth"
____exports.PlaydateSoundWave.POPhase = 5
____exports.PlaydateSoundWave[____exports.PlaydateSoundWave.POPhase] = "POPhase"
____exports.PlaydateSoundWave.PODigital = 6
____exports.PlaydateSoundWave[____exports.PlaydateSoundWave.PODigital] = "PODigital"
____exports.PlaydateSoundWave.POVosim = 7
____exports.PlaydateSoundWave[____exports.PlaydateSoundWave.POVosim] = "POVosim"
____exports.PlaydateSoundLfoType = PlaydateSoundLfoType or ({})
____exports.PlaydateSoundLfoType.Square = 0
____exports.PlaydateSoundLfoType[____exports.PlaydateSoundLfoType.Square] = "Square"
____exports.PlaydateSoundLfoType.Triangle = 1
____exports.PlaydateSoundLfoType[____exports.PlaydateSoundLfoType.Triangle] = "Triangle"
____exports.PlaydateSoundLfoType.Sine = 2
____exports.PlaydateSoundLfoType[____exports.PlaydateSoundLfoType.Sine] = "Sine"
____exports.PlaydateSoundLfoType.SampleAndHold = 3
____exports.PlaydateSoundLfoType[____exports.PlaydateSoundLfoType.SampleAndHold] = "SampleAndHold"
____exports.PlaydateSoundLfoType.SawtoothUp = 4
____exports.PlaydateSoundLfoType[____exports.PlaydateSoundLfoType.SawtoothUp] = "SawtoothUp"
____exports.PlaydateSoundLfoType.SawtoothDown = 5
____exports.PlaydateSoundLfoType[____exports.PlaydateSoundLfoType.SawtoothDown] = "SawtoothDown"
____exports.PlaydateSoundTwoPoleFilterType = PlaydateSoundTwoPoleFilterType or ({})
____exports.PlaydateSoundTwoPoleFilterType.LowPass = 0
____exports.PlaydateSoundTwoPoleFilterType[____exports.PlaydateSoundTwoPoleFilterType.LowPass] = "LowPass"
____exports.PlaydateSoundTwoPoleFilterType.HighPass = 1
____exports.PlaydateSoundTwoPoleFilterType[____exports.PlaydateSoundTwoPoleFilterType.HighPass] = "HighPass"
____exports.PlaydateSoundTwoPoleFilterType.BandPass = 2
____exports.PlaydateSoundTwoPoleFilterType[____exports.PlaydateSoundTwoPoleFilterType.BandPass] = "BandPass"
____exports.PlaydateSoundTwoPoleFilterType.Notch = 3
____exports.PlaydateSoundTwoPoleFilterType[____exports.PlaydateSoundTwoPoleFilterType.Notch] = "Notch"
____exports.PlaydateSoundTwoPoleFilterType.PEQ = 4
____exports.PlaydateSoundTwoPoleFilterType[____exports.PlaydateSoundTwoPoleFilterType.PEQ] = "PEQ"
____exports.PlaydateSoundTwoPoleFilterType.LowShelf = 5
____exports.PlaydateSoundTwoPoleFilterType[____exports.PlaydateSoundTwoPoleFilterType.LowShelf] = "LowShelf"
____exports.PlaydateSoundTwoPoleFilterType.HighShelf = 6
____exports.PlaydateSoundTwoPoleFilterType[____exports.PlaydateSoundTwoPoleFilterType.HighShelf] = "HighShelf"
return ____exports
