name: Main

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    main:
        name: Health check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: pnpm/action-setup@v4

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: CI tstl-plugin
              run: pnpm exec nx run-many -t lint test build -p tstl-plugin

            - name: Move tstl-plugin build to CLI
              run: pnpm exec nx run tstl-plugin:move-build-to-cli

            - name: CI affected projects
              run: NODE_OPTIONS=--experimental-vm-modules pnpm exec nx affected -t lint test build --exclude=tstl-plugin

            - name: Run post build on affected projects
              run: pnpm exec nx affected -t post-build
